inherit_from: .rubocop_todo.yml
require:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'ext/**/*'
    - 'lib/couchbase/protostellar/generated/**/*'
    # Copied from Rails v6.1.0-38-gbf165e3e19
    - 'test/active_support/behaviors/*.rb'
    - 'test/active_support/behaviors.rb'

Metrics/ParameterLists:
  Max: 30

Layout/LineLength:
  Max: 140

Metrics/BlockNesting:
  Max: 4

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Style/Lambda:
  EnforcedStyle: lambda

Style/SymbolArray:
  EnforcedStyle: brackets

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

