module Couchbase
  module Protostellar
    module RequestGenerator
      class Search
        MATCH_QUERY_OPERATOR_MAP: Hash[Symbol, Symbol]
        HIGHLIGHT_STYLE_MAP: Hash[Symbol?, Symbol]
        SCAN_CONSISTENCY_MAP: Hash[Symbol, Symbol]

        def search_query_request: (String index_name, untyped query, untyped options) -> untyped

        private

        def create_search_request: (
            untyped proto_request,
            Symbol rpc,
            untyped options,
            idempotent: bool
          ) -> Request

        def create_query: (untyped query) -> [untyped, Symbol]
        def create_boolean_field_query: (untyped query) -> untyped
        def create_boolean_query: (untyped query) -> untyped
        def create_conjunction_query: (untyped query) -> untyped
        def create_disjunction_query: (untyped query) -> untyped
        def create_date_range_query: (untyped query) -> untyped
        def create_doc_id_query: (untyped query) -> untyped
        def create_geo_bounding_box_query: (untyped query) -> untyped
        def create_geo_distance_query: (untyped query) -> untyped
        def create_geo_polygon_query: (untyped query) -> untyped
        def create_match_all_query: (untyped query) -> untyped
        def create_match_none_query: (untyped query) -> untyped
        def create_match_phrase_query: (untyped query) -> untyped
        def create_match_query: (untyped query) -> untyped
        def create_numeric_range_query: (untyped query) -> untyped
        def create_phrase_query: (untyped query) -> untyped
        def create_prefix_query: (untyped query) -> untyped
        def create_query_string_query: (untyped query) -> untyped
        def create_regexp_query: (untyped query) -> untyped
        def create_term_query: (untyped query) -> untyped
        def create_term_range_query: (untyped query) -> untyped
        def create_wildcard_query: (untyped query) -> untyped

        def get_sort: (untyped options) -> untyped
      end
    end
  end
end
