module Couchbase
  module Protostellar
    module Retry
      class Orchestrator
        def self.maybe_retry: (Request, Reason) -> void
        def self.get_controlled_backoff: (Request) -> Integer
      end
    end
  end
end
