# frozen_string_literal: true

#  Copyright 2026-Present Couchbase, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

require "bundler/gem_tasks"
require "rubocop/rake_task"

desc "Generate YARD documentation"
task :doc do
  require "couchbase/opentelemetry/version"
  input_dir = File.join(__dir__, "lib")
  output_dir = File.join(__dir__, "doc", "couchbase-ruby-client-#{Couchbase::OpenTelemetry::VERSION}")
  rm_rf output_dir
  sh "bundle exec yard doc --no-progress --hide-api private --output-dir #{output_dir} #{input_dir} --main README.md"
  puts "#{File.realpath(output_dir)}/index.html"
end

desc "An alias for documentation generation task"
task :docs => :doc

desc "Display stats on undocumented things"
task :undocumented => :doc do
  sh "yard stats --list-undoc --compact"
end

RuboCop::RakeTask.new
