#!/usr/bin/env ruby
# Author:: Couchbase <info@couchbase.com>
# Copyright:: 2013 Couchbase, Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'bundler'
Bundler.setup

require 'couchbase'

$LOAD_PATH.unshift(File.dirname(__FILE__))
require 'gzip_transcoder'
require 'options'

STDERR.puts "Run with arguments: #{OPTIONS.inspect}"
begin
  conn = Couchbase.connect(OPTIONS)
  conn.transcoder = GzipTranscoder.new

  ARGV.each do |filename|
    STDERR.print "store \"#{filename}\" ... "
    if File.exists?(filename)
      conn.set(filename, File.read(filename))
      STDERR.puts "ok"
    else
      STDERR.puts "not found"
    end
  end
rescue Couchbase::Error::Base => ex
  STDERR.puts "ERROR: #{ex}"
  exit 1
end
