#  Copyright 2023. Couchbase, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

module Couchbase
  module Protostellar
    module Management
      class BucketManager
        @client: Client
        @request_generator: RequestGenerator::Admin::Bucket

        def initialize: (Client client) -> void

        def create_bucket: (
            Couchbase::Management::BucketSettings settings,
            Couchbase::Management::Options::Bucket::CreateBucket options
          ) -> void

        def update_bucket: (
            Couchbase::Management::BucketSettings settings,
            Couchbase::Management::Options::Bucket::UpdateBucket options
          ) -> void

        def drop_bucket: (
            String bucket_name,
            Couchbase::Management::Options::Bucket::DropBucket options
          ) -> void

        def get_bucket: (
            String bucket_name,
            Couchbase::Management::Options::Bucket::GetBucket options
          ) -> Couchbase::Management::BucketSettings

        def get_all_buckets: (
            Couchbase::Management::Options::GetAllBuckets options
          ) -> Array[Couchbase::Management::BucketSettings]

        def flush_bucket: (
            String bucket_name,
            Couchbase::Management::Options::Bucket::FlushBucket options
          ) -> void
      end
    end
  end
end
