module Couchbase
  module Protostellar
    module Management
      class CollectionQueryIndexManager
        @client: Client
        @bucket_name: String
        @scope_name: String
        @collection_name: String
        @request_generator: RequestGenerator::Admin::Query

        def initialize: (
            client: Client,
            bucket_name: String,
            scope_name: String,
            collection_name: String
          ) -> void

        def get_all_indexes: (untyped options) -> Array[untyped]
        def create_index: (String index_name, Array[String] fields, untyped options) -> void
        def create_primary_index: (untyped options) -> void
        def drop_index: (String index_name, untyped options) -> void
        def drop_primary_index: (untyped options) -> void
        def build_deferred_indexes: (untyped options) -> void
        def watch_indexes: (Array[String] index_names, (Integer | _CanInMilliseconds) timeout, untyped options) -> void

        private

        def validate_options: (untyped options) -> void
      end
    end
  end
end
