# frozen_string_literal: true

source "https://rubygems.org"

gem "couchbase"
gem "couchbase-opentelemetry"

gem "opentelemetry-exporter-otlp"
gem "opentelemetry-exporter-otlp-metrics"
gem "opentelemetry-metrics-sdk"
gem "opentelemetry-sdk"
