#  Copyright 2022-Present Couchbase, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

module Couchbase
  module Protostellar
    class Cluster
      include _Cluster
      VALID_CONNECTION_STRING_PARAMS: Array[String]

      attr_reader client: Client

      @query_request_generator: RequestGenerator::Query
      @search_request_generator: RequestGenerator::Search

      def self.connect: (String connection_string, untyped options) -> untyped
      def self.parse_connection_string_params: (String connection_string) -> Hash[String, untyped]

      def initialize: (untyped connection_string, ?untyped options) -> void

      def disconnect: () -> void
      def bucket: (String name) -> Bucket
      def buckets: () -> Management::BucketManager
      def query_indexes: () -> Management::QueryIndexManager

      def query: (
          String statement,
          Couchbase::Options::Query options
        ) -> Couchbase::Cluster::QueryResult

      def search_query: (
          String index_name,
          Couchbase::Cluster::SearchQuery query,
          Couchbase::Options::Search options
        ) -> Couchbase::Cluster::SearchResult
    end
  end
end
