#  Copyright 2022-Present Couchbase, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

module Couchbase
  module Protostellar
    class Collection
      @client: Client
      @bucket_name: String
      @scope_name: String
      @kv_request_generator: RequestGenerator::KV

      attr_reader name: String

      def initialize: (Client, String, String, String) -> void

      def get: (String, Couchbase::Options::Get) -> Couchbase::Collection::GetResult

      def get_and_touch: (String, untyped, Couchbase::Options::GetAndTouch) -> Couchbase::Collection::GetResult

      def get_and_lock: (String, untyped, Couchbase::Options::GetAndLock) -> Couchbase::Collection::GetResult

      def unlock: (String, Integer, Couchbase::Options::Unlock) -> void

      def upsert: (String, untyped, Couchbase::Options::Upsert) -> Couchbase::Collection::MutationResult

      def remove: (String, Couchbase::Options::Remove) -> Couchbase::Collection::MutationResult

      def insert: (String, untyped, Couchbase::Options::Insert) -> Couchbase::Collection::MutationResult

      def replace: (String, untyped, Couchbase::Options::Replace) -> Couchbase::Collection::MutationResult

      def exists: (String, ExistsOptions) -> Couchbase::Collection::ExistsResult
    end
  end
end
