#  Copyright 2022-Present Couchbase, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

module Couchbase
  module Protostellar
    class ConnectOptions
      @client_certificate: String?
      @password: String?
      @private_key: String?
      @root_certificates: String?
      @username: String?

      def initialize: (?username: String? username, ?password: String? password, ?root_certificates: String? root_certificates, ?client_certificate: String? client_certificate, ?private_key: String? private_key) -> void

      def grpc_credentials: () -> untyped

      def grpc_channel_args: () -> untyped

      def grpc_call_metadata: () -> Hash[untyped, untyped]
    end
  end
end
