name: validate-fit-performer
permissions: {}

on:
  pull_request:
    branches:
      - main
      - release*

    paths:
      - 'fit-performer/**'
      - '.github/workflows/validate-fit-performer.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event_name != 'push'

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true

      - run: |
          docker build -f fit-performer/Dockerfile .
