name: validate-fit-performer
permissions: {}

on:
  pull_request:
    branches:
      - main
      - release*

    paths:
      - 'fit-performer/**'
      - '.github/workflows/validate-fit-performer.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event_name != 'push'

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true

      - run: |
          docker build -f fit-performer/Dockerfile .
